<?php

/**
 * ActualizacionesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActualizacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActualizacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actualizaciones');
    }

    // NUEVAS FUNCIONES

    // Obtener obras sociales
    public static function prepararRegistros()
    {

         // preparar registros que deben ser actualizados
        $sql ="UPDATE tmp_pacientes tmp JOIN pacientes pac ON tmp.documento = pac.nrodoc SET actualizar = 1;";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        return $q->execute($sql);

    }

    // Desactivar Registros
    public static function desactivarRegistros()
    {

         // desactivar registros
        $sql ="UPDATE pacientes pac JOIN (SELECT DISTINCT codOsocial FROM tmp_pacientes ) as tmp ON pac.idobrasocial = tmp.codOSocial LEFT JOIN tmp_pacientes tmppac ON pac.nrodoc = tmppac.documento
                SET pac.activo = false WHERE tmppac.documento IS NULL;";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        return $q->execute($sql);

    }

    // Obtener obras sociales
    public static function insertarPacientes()
    {

         // actualizar designaciones
        $sql ="INSERT INTO `pacientes`
                SELECT NULL, nombre, apellido, sexo, documento, fechanac, fechanac, codCiudad, ecivil, email, celular, telefono, direccion, titular, parentesco, trabajo, '', trabajo, jerarquia, '', anotaciones, 1 as activo, nroafiliado, historial, NULL, codProvincia, codOSocial, codPlan, NOW(), NOW(),1,1, iva
                FROM tmp_pacientes WHERE actualizar = 0 GROUP BY documento;";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        return $q->execute($sql);

    }

    // Obtener obras sociales
    /* public static function obtenerRegistrosAInsertar()
    {
       // $sql ="SELECT tmp.* FROM tmp_pacientes tmp LEFT JOIN pacientes pac ON tmp.email = pac.email WHERE pac.email IS NULL GROUP BY tmp.email; ";
        $sql ="SELECT tmp.* FROM tmp_pacientes tmp LEFT JOIN pacientes pac ON tmp.documento = pac.nrodoc WHERE pac.nrodoc IS NULL GROUP BY tmp.documento; ";


		$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    } */

    // Obtener obras sociales
    public static function obtenerRegistrosAActualizar($campo_en_pacientes,$campo, $tipo_campo)
    {
        //$sql ="SELECT tmp.* FROM tmp_pacientes tmp JOIN pacientes pac ON tmp.email = pac.email GROUP BY tmp.email; ";
        $sql ="UPDATE pacientes pac JOIN tmp_pacientes tmp ON pac.nrodoc = tmp.documento SET activo = true, pac.".$campo_en_pacientes." = tmp.".$campo." WHERE tmp.actualizar = 1 ";

        if ($tipo_campo=='N'){
            $sql .=" AND tmp.".$campo." > 0 ";
        } else {
            $sql .=" AND tmp.".$campo." IS NOT NULL AND tmp.".$campo." <> '' ";
        }

        $sql .=" ; ";
        //$sql .=" GROUP BY tmp.documento; ";

		//$q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $sql; // RETORNA el string con la consulta solamente
    }
}
