<?php

/**
 * AtencionesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AtencionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AtencionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Atenciones');
    }

    // Obtener obras sociales
    public static function obtenerAtenciones()
    {
        $sql ="SELECT at.id, at.nrodoc, at.mes, at.anio, at.matricula, at.fecha, at.pieza, at.caras, at.tratamiento, at.importe, at.coseguro, at.bono, at.importe,
            pac.apellido, pac.nombre, os.denominacion, os.abreviada as obrasocial, concat(per.apellido,', ' , per.nombre) as profesional
            FROM atenciones at JOIN pacientes pac ON at.nrodoc = pac.nrodoc
            JOIN obras_sociales os ON at.idobrasocial = os.idobrasocial
            JOIN personas per ON at.matricula = per.nrolector ";

		/* if($estado !== NULL)
		    $sql .=  " WHERE t.activo = ".$estado." ";	*/

		$sql .= " ORDER BY os.abreviada, at.fecha DESC;";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }
}
