<?php

/**
 * GrupoTratamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoTratamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoTratamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoTratamiento');
    }
}