<?php

/**
 * OdontogramaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OdontogramaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OdontogramaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Odontograma');
    }
}