<?php

/**
 * OdontogramaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OdontogramaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OdontogramaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Odontograma');
    }

     // Obtener ultimo odontograma
    public static function obtenerUltimo($idpaciente)
    {
        $sql ="SELECT o.id, o.matricula, o.idpaciente, o.infodontograma, o.created_at FROM odontograma o JOIN 
        (SELECT MAX(created_at) as maxfecha FROM odontograma WHERE idpaciente= ".$idpaciente.") as ultimo ON o.created_at= ultimo.maxfecha WHERE o.idpaciente = ".$idpaciente.";";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }

    // Obtener ultimo odontograma anterior a fecha
    public static function obtenerUltimoAnteriorAfecha($idpaciente, $fecha)
    {
        $sql ="SELECT o.id, o.matricula, o.idpaciente, o.infodontograma, o.created_at FROM odontograma o 
        JOIN (SELECT MAX(created_at) as maxfecha FROM odontograma WHERE created_at<'".$fecha."' GROUP BY idpaciente HAVING idpaciente= ".$idpaciente.") as ultimo ON o.created_at= ultimo.maxfecha WHERE o.idpaciente = ".$idpaciente.";";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }

     // Obtener ultimo odontograma
    public static function obtenerUltimoOdontograma($matricula, $idpaciente)
    {
        $sql ="SELECT o.id, o.matricula, o.idpaciente, o.infodontograma, o.created_at FROM odontograma o JOIN 
        (SELECT MAX(created_at) as maxfecha FROM odontograma WHERE idpaciente= ".$idpaciente." AND matricula= ".$matricula.") as ultimo ON o.created_at= ultimo.maxfecha WHERE o.idpaciente = ".$idpaciente." AND o.matricula= ".$matricula.";";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }


}