<?php

/**
 * PacientesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pacientes');
    }

    // Busca el paciente por dni
    public static function getPacienteIdByNroDoc($criterio) {
		$q = Doctrine_Query::create()
	  		->select("*")
	 		->from("Pacientes p")
	 		->where("p.nrodoc = ".$criterio)
	    	->fetchOne();

        return $q;
    }

    // Obtener pacientes
    public static function obtenerPacientes($apellido=NULL,$idobrasocial=NULL, $nrodoc=NULL, $limit=NULL)
    {
        $sql ="SELECT pac.id, pac.nombre, pac.apellido, pac.idsexo, pac.nrodoc, pac.fechanac, pac.fechaingreso, pac.email, pac.nroafiliado, os.denominacion as obrasocial, os.abreviada
            FROM pacientes pac LEFT JOIN obras_sociales os ON pac.idobrasocial = os.idobrasocial WHERE 1=1 ";

        if($apellido !== NULL)
            $sql .=  " AND pac.apellido LIKE  '%".$apellido."%' ";

        if($nrodoc !== NULL)
            $sql .=  " AND pac.nrodoc = ".$nrodoc." ";

        if($idobrasocial !== NULL)
            $sql .=  " AND pac.idobrasocial = ".$idobrasocial." ";

        $sql .= " ORDER BY pac.apellido ";

        if($limit !== NULL)
            $sql .=  " LIMIT ".$limit." ";

        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);

        return $q;
    }

}
