<?php

/**
 * TratamientosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TratamientosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TratamientosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tratamientos');
    }
}