sistemas:
  class: sfDoctrineRouteCollection
  options:
    model:                sistemas
    module:               sistemas
    prefix_path:          /sistemas
    column:               id
    with_wildcard_routes: true

inscripcionesmesas:
  class: sfDoctrineRouteCollection
  options:
    model:                inscripcionesmesas
    module:               inscripcionesmesas
    prefix_path:          /inscripcionesmesas
    column:               idinscripcion
    with_wildcard_routes: true

personasegresadas:
  class: sfDoctrineRouteCollection
  options:
    model:                personas
    module:               personasegresadas
    prefix_path:          /personasegresadas
    column:               idpersona
    with_wildcard_routes: true

reglamentos:
  class: sfDoctrineRouteCollection
  options:
    model:                reglamentos
    module:               reglamentos
    prefix_path:          /reglamentos
    column:               id
    with_wildcard_routes: true

calendar:
  class: sfDoctrineRouteCollection
  options:
    model:                calendar
    module:               calendar
    prefix_path:          /calendar
    column:               id
    with_wildcard_routes: true

auditoria:
  class: sfDoctrineRouteCollection
  options:
    model:                auditoria
    module:               auditoria
    prefix_path:          /auditoria
    column:               id
    with_wildcard_routes: true

estados_carreras:
  class: sfDoctrineRouteCollection
  options:
    model:                EstadosCarreras
    module:               estadoscarreras
    prefix_path:          /estadoscarreras
    column:               idestadocarrera
    with_wildcard_routes: true

obras_sociales:
  class: sfDoctrineRouteCollection
  options:
    model:                ObrasSociales
    module:               obrassociales
    prefix_path:          /obrassociales
    column:               idobrasocial
    with_wildcard_routes: true    

modalidades_carreras:
  class: sfDoctrineRouteCollection
  options:
    model:                ModalidadesCarreras
    module:               modalidadescarreras
    prefix_path:          /modalidadescarreras
    column:               idmodalidad
    with_wildcard_routes: true

detalle_nota:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleNota
    module:               detallenota
    prefix_path:          /detallenota
    column:               iddetallenota
    with_wildcard_routes: true

estados_planes:
  class: sfDoctrineRouteCollection
  options:
    model:                EstadosPlanes
    module:               estadosplanes
    prefix_path:          /estadosplanes
    column:               idestadoplan
    with_wildcard_routes: true

modos_egreso:
  class: sfDoctrineRouteCollection
  options:
    model:                ModosEgreso
    module:               modosegreso
    prefix_path:          /modosegreso
    column:               idmodoegreso
    with_wildcard_routes: true

carreras:
  class: sfDoctrineRouteCollection
  options:
    model:                carreras
    module:               carreras
    prefix_path:          /carreras
    column:               idcarrera
    with_wildcard_routes: true

escalas_notas:
  class: sfDoctrineRouteCollection
  options:
    model:                EscalasNotas
    module:               escalasnotas
    prefix_path:          /escalasnotas
    column:               idescalanota
    with_wildcard_routes: true

titulos_planes:
  class: sfDoctrineRouteCollection
  options:
    model:                TitulosPlanes
    module:               titulosplanes
    prefix_path:          /titulosplanes
    column:               idtituloplan
    with_wildcard_routes: true

titulos:
  class: sfDoctrineRouteCollection
  options:
    model:                Titulos
    module:               titulos
    prefix_path:          /titulos
    column:               idtitulo
    with_wildcard_routes: true

tipos_titulos:
  class: sfDoctrineRouteCollection
  options:
    model:                TiposTitulos
    module:               tipostitulos
    prefix_path:          /tipostitulos
    column:               idtipotitulo
    with_wildcard_routes: true

tipos_carreras:
  class: sfDoctrineRouteCollection
  options:
    model:                TiposCarreras
    module:               tiposcarreras
    prefix_path:          /tiposcarreras
    column:               idtipocarrera
    with_wildcard_routes: true

calendarios:
  class: sfDoctrineRouteCollection
  options:
    model:                calendarios
    module:               calendarios
    prefix_path:          /calendarios
    column:               idcalendario
    with_wildcard_routes: true

materias_planes:
  class: sfDoctrineRouteCollection
  options:
    model:                MateriasPlanes
    module:               materias_planes
    prefix_path:          /materias_planes
    column:               idmateriaplan
    with_wildcard_routes: true
    
materias:
  class: sfDoctrineRouteCollection
  options:
    model:                Materias
    module:               materias
    prefix_path:          /materias
    column:               idmateria
    with_wildcard_routes: true

planes_estudios:
  class: sfDoctrineRouteCollection
  options:
    model:                PlanesEstudios
    module:               planes_estudios
    prefix_path:          /planes_estudios
    column:               idplanestudio
    with_wildcard_routes: true

noticias:
  class: sfDoctrineRouteCollection
  options:
    model:                noticias
    module:               noticias
    prefix_path:          /noticias
    column:               id
    with_wildcard_routes: true

encuestas:
  class: sfDoctrineRouteCollection
  options:
    model:                encuestas
    module:               encuestas
    prefix_path:          /encuestas
    column:               idencuesta
    with_wildcard_routes: true

solicitudes:
  class: sfDoctrineRouteCollection
  options:
    model:                solicitudes
    module:               solicitudes
    prefix_path:          /solicitudes
    column:               id
    with_wildcard_routes: true

expedientes:
  class: sfDoctrineRouteCollection
  options:
    model:                expedientes
    module:               expedientes
    prefix_path:          /expedientes
    column:               id
    with_wildcard_routes: true

derivaciones:
  class: sfDoctrineRouteCollection
  options:
    model:                derivaciones
    module:               derivaciones
    prefix_path:          /derivaciones
    column:               id
    with_wildcard_routes: true

encuestas:
  class: sfDoctrineRouteCollection
  options:
    model:                encuestas
    module:               encuestas
    prefix_path:          /encuestas
    column:               idencuesta
    with_wildcard_routes: true

equivalencias:
  class: sfDoctrineRouteCollection
  options:
    model:                equivalencias
    module:               equivalencias
    prefix_path:          /equivalencias
    column:               id
    with_wildcard_routes: true

grupomenu:
  class: sfDoctrineRouteCollection
  options:
    model:                grupomenu
    module:               grupomenu
    prefix_path:          /grupomenu
    column:               id
    with_wildcard_routes: true

menu:
  class: sfDoctrineRouteCollection
  options:
    model:                menu
    module:               menu
    prefix_path:          /menu
    column:               id
    with_wildcard_routes: true

sedes:
  class: sfDoctrineRouteCollection
  options:
    model:                sedes
    module:               sedes
    prefix_path:          /sedes
    column:               idsede
    with_wildcard_routes: true
   
api_obtener_idusuario:
  url:   /api/obteneridusuario.:sf_format
  param: { module: api, action: obteneridusuario }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_carreras_inscripto:
  url:   /api/obtenercarrerasinscripto.:sf_format
  param: { module: api, action: obtenercarrerasinscripto }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_calendario:
  url:   /api/obtenercalendario.:sf_format
  param: { module: api, action: obtenercalendario }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_historial:
  url:   /api/obtenerhistorial.:sf_format
  param: { module: api, action: obtenerhistorial }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_solicitudes:
  url:   /api/obtenersolicitudes.:sf_format
  param: { module: api, action: obtenersolicitudes }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_guardar_solicitud:
  url:   /api/guardarsolicitud.:sf_format
  param: { module: api, action: guardarsolicitud }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_solicitud:
  url:   /api/obtenersolicitud.:sf_format
  param: { module: api, action: obtenersolicitud }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_materias_cursar:
  url:   /api/obtenermateriascursar.:sf_format
  param: { module: api, action: obtenermateriascursar }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_materias_inscriptas:
  url:   /api/obtenermateriasinscriptas.:sf_format
  param: { module: api, action: obtenermateriasinscriptas }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_inscribir_materia:
  url:   /api/inscribirmateria.:sf_format
  param: { module: api, action: inscribirmateria }
  requirements:
    sf_method: get
    sf_format: (?:json)


api_eliminar_inscripcion_materia:
  url:   /api/eliminarinscripcionmateria.:sf_format
  param: { module: api, action: eliminarinscripcionmateria }
  requirements:
    sf_method: get
    sf_format: (?:json)


api_obtener_mesas_rendir:
  url:   /api/obtenermesasrendir.:sf_format
  param: { module: api, action: obtenermesasrendir }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_obtener_mesas_inscriptas:
  url:   /api/obtenermesasinscriptas.:sf_format
  param: { module: api, action: obtenermesasinscriptas }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_inscribir_mesa:
  url:   /api/inscribirmesa.:sf_format
  param: { module: api, action: inscribirmesa }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_eliminar_inscripcion_mesa:
  url:   /api/eliminarinscripcionmesa.:sf_format
  param: { module: api, action: eliminarinscripcionmesa }
  requirements:
    sf_method: get
    sf_format: (?:json)

api_solicitar_libredeuda:
  url:   /api/solicitarlibredeuda.:sf_format
  param: { module: api, action: solicitarlibredeuda }
  requirements:
    sf_method: get
    sf_format: (?:json)

sectores:
  class: sfDoctrineRouteCollection
  options:
    model:                sectores
    module:               sectores
    prefix_path:          /sectores
    column:               id
    with_wildcard_routes: true

llamadosturno:
  class: sfDoctrineRouteCollection
  options:
    model:                llamadosturno
    module:               llamadosturno
    prefix_path:          /llamadosturno
    column:               idllamado
    with_wildcard_routes: true

empleados:
  class: sfDoctrineRouteCollection
  options:
    model:                empleados
    module:               empleados
    prefix_path:          /empleados
    column:               id
    with_wildcard_routes: true

    
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules 
#homepage:
#  url:   /
  # param: { module: ingreso, action: index }
#  param: { module: sfGuardAuth, action: signin }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
        
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_user:
  url:   /user
  param: { module: sfGuardUser, action: index }

sf_guard_group:
  url:   /group
  param: { module: sfGuardGroup, action: index }

sf_guard_permission:
  url:   /permission
  param: { module: sfGuardPermission, action: index }

libredeuda:
  url:   /libredeuda
  param: { module: libredeuda, action: index }

ingreso:
  url:   /
  param: { module: ingreso, action: index }

alumat:
  url:   /alumat
  param: { module: alumat, action: index }

encuestasalumnos:
  url:   /encuestasalumnos
  param: { module: encuestasalumnos, action: index }